# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: '#'}
- {icon: 'envelope', link: '#'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

post_date_prefix: 'Written on'
